-- ==========================================
-- 5. DESTINATIONS UPGRADE & PLAYLISTS
-- ==========================================

-- A. UPGRADE DESTINATIONS TABLE
-- Add new columns if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'trek_level') THEN
        ALTER TABLE destinations ADD COLUMN trek_level TEXT CHECK (trek_level IN ('Mudah', 'Sedang', 'Sulit', '-'));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'is_trending') THEN
        ALTER TABLE destinations ADD COLUMN is_trending BOOLEAN DEFAULT FALSE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'is_recommended') THEN
        ALTER TABLE destinations ADD COLUMN is_recommended BOOLEAN DEFAULT FALSE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'season') THEN
        ALTER TABLE destinations ADD COLUMN season TEXT CHECK (season IN ('All Season', 'Kemarau', 'Hujan'));
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'visitor_percent') THEN
        ALTER TABLE destinations ADD COLUMN visitor_percent INTEGER DEFAULT 0;
    END IF;
    
    -- Ensure status column has correct constraint if creating new (already exists usually, but good to check or note)
    -- existing constraint might be text.
END $$;

-- B. PLAYLISTS SETUP
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    thumbnail_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS playlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    display_order INTEGER DEFAULT 0,
    UNIQUE(playlist_id, destination_id)
);

-- RLS FOR PLAYLISTS
ALTER TABLE playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlist_items ENABLE ROW LEVEL SECURITY;

-- Public Read
CREATE POLICY "Public read playlists" ON playlists FOR SELECT USING (true);
CREATE POLICY "Public read playlist_items" ON playlist_items FOR SELECT USING (true);

-- Admin Write
CREATE POLICY "Admin full playlists" ON playlists USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full playlist_items" ON playlist_items USING (auth.role() = 'authenticated');

-- Refresh
NOTIFY pgrst, 'reload schema';
