-- ==========================================
-- 6. DETAIL PAGE BUILDER SUPPORT
-- ==========================================

-- A. DETAIL CONFIGURATION COLUMN
-- Stores layout order, active sections, and rich text blocks not covered by standard columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'detail_config') THEN
        ALTER TABLE destinations ADD COLUMN detail_config JSONB DEFAULT '{}'::jsonb;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'facilities') THEN
        ALTER TABLE destinations ADD COLUMN facilities TEXT[];
    END IF;
END $$;

-- B. PHOTO SPOTS TABLE (For Gallery/Spots Section)
CREATE TABLE IF NOT EXISTS photo_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_path TEXT,
    description TEXT,
    best_time TEXT,
    location_hint TEXT, -- e.g. "Near entrance"
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- C. NEARBY PLACES (For Culinary/Basecamp)
CREATE TABLE IF NOT EXISTS nearby_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('culinary', 'lodging', 'souvenir', 'basecamp', 'other')),
    distance TEXT, -- e.g "500m"
    note TEXT, -- Recommendation note
    maps_url TEXT,
    image_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- D. VISITOR TIPS (Optional, can also just be in detail_config JSON)
-- We'll keep simple tips in detail_config or a simple text array column if desired, 
-- but user asked for "Tips Kunjungan" section. 
-- Let's put specific tips in a table if they are shared, but usually they are specific.
-- We will store them in `detail_config` -> `tips` array.

-- RLS
ALTER TABLE photo_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE nearby_places ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read spots" ON photo_spots FOR SELECT USING (true);
CREATE POLICY "Public read nearby" ON nearby_places FOR SELECT USING (true);
CREATE POLICY "Admin all spots" ON photo_spots USING (auth.role() = 'authenticated');
CREATE POLICY "Admin all nearby" ON nearby_places USING (auth.role() = 'authenticated');

NOTIFY pgrst, 'reload schema';
