-- ==========================================
-- 1. NEWSLETTER SUBSCRIBERS SETUP
-- ==========================================

-- Create table if not exists
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    interests TEXT[] DEFAULT '{}', -- Array for interests
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Ensure 'interests' column exists (safe even if table existed before)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'newsletter_subscribers' AND column_name = 'interests') THEN
        ALTER TABLE newsletter_subscribers ADD COLUMN interests TEXT[] DEFAULT '{}';
    END IF;
END $$;

-- Enable RLS
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public inserts
DROP POLICY IF EXISTS "Enable insert for all users" ON newsletter_subscribers;
CREATE POLICY "Enable insert for all users" 
ON newsletter_subscribers FOR INSERT 
WITH CHECK (true);

-- ==========================================
-- 2. CONTACT MESSAGES SETUP
-- ==========================================

-- Create table if not exists
CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public inserts
DROP POLICY IF EXISTS "Enable insert for public" ON contact_messages;
CREATE POLICY "Enable insert for public" 
ON contact_messages FOR INSERT 
WITH CHECK (true);

-- ==========================================
-- 3. REFRESH SCHEMA CACHE
-- ==========================================
-- This forces the API to recognize the new tables/columns immediately
NOTIFY pgrst, 'reload schema';
