-- ==============================================================================
-- EXPLORE LUMAJANG - FULL CMS DATABASE SETUP
-- ==============================================================================
-- This script consolidates all module requirements into a single execution flow.
-- It is designed to be idempotent (safe to run multiple times).
-- 
-- MODULES COVERED:
-- 1. Destinations (Core, Upgrades, Configs, Spots, Nearby)
-- 2. Page & Home Management (Hero, Slider, configs)
-- 3. Tips & Articles (Blog + Checklists)
-- 4. User Interaction (Newsletter, Contact, Favorites)
-- 5. Playlists (Curated Lists)
-- ==============================================================================

-- 1. DESTINATIONS MODULE
-- ==============================================================================

-- A. Core Upgrades to 'destinations' table
DO $$
BEGIN
    -- Basic Info & Metrics
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'trek_level') THEN
        ALTER TABLE destinations ADD COLUMN trek_level TEXT CHECK (trek_level IN ('Mudah', 'Sedang', 'Sulit', '-'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'season') THEN
        ALTER TABLE destinations ADD COLUMN season TEXT CHECK (season IN ('All Season', 'Kemarau', 'Hujan'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'visitor_percent') THEN
        ALTER TABLE destinations ADD COLUMN visitor_percent INTEGER DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'mood_tags') THEN
        ALTER TABLE destinations ADD COLUMN mood_tags TEXT[] DEFAULT '{}';
    END IF;

    -- Marketing Flags
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'is_trending') THEN
        ALTER TABLE destinations ADD COLUMN is_trending BOOLEAN DEFAULT FALSE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'is_recommended') THEN
        ALTER TABLE destinations ADD COLUMN is_recommended BOOLEAN DEFAULT FALSE;
    END IF;

    -- Detail Page Builder Config
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'detail_config') THEN
        ALTER TABLE destinations ADD COLUMN detail_config JSONB DEFAULT '{}'::jsonb;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'destinations' AND column_name = 'facilities') THEN
        ALTER TABLE destinations ADD COLUMN facilities TEXT[];
    END IF;
END $$;

-- B. Sub-tables for Destinations (Spots & Nearby)
CREATE TABLE IF NOT EXISTS photo_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_path TEXT,
    description TEXT,
    best_time TEXT,
    location_hint TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS nearby_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT CHECK (type IN ('culinary', 'lodging', 'souvenir', 'basecamp', 'other')),
    distance TEXT,
    note TEXT,
    maps_url TEXT,
    image_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. PAGE & HOME MANAGEMENT
-- ==============================================================================
CREATE TABLE IF NOT EXISTS page_sections (
    section_key TEXT PRIMARY KEY, -- e.g. 'home_hero', 'home_districts', 'global_configs'
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. TIPS & ARTICLES MODULE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category TEXT DEFAULT 'Tips',
    cover_image TEXT,
    content TEXT,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT REFERENCES articles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    items JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. PLAYLISTS MODULE
-- ==============================================================================
CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    thumbnail_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS playlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT REFERENCES playlists(id) ON DELETE CASCADE,
    destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
    display_order INTEGER DEFAULT 0,
    UNIQUE(playlist_id, destination_id)
);

-- 5. USER INTERACTION MODULE
-- ==============================================================================
-- Newsletter
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    interests TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Contact Form
CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new' CHECK (status IN ('new', 'read', 'replied')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Favorites (Collections)
CREATE TABLE IF NOT EXISTS favorites (
  user_id UUID REFERENCES auth.users NOT NULL,
  destination_id BIGINT REFERENCES destinations(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (user_id, destination_id)
);

-- User Roles (Admin/User)
CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);



-- ==============================================================================
-- SECURITY POLICIES (RLS)
-- ==============================================================================

-- Enable RLS on all tables
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE photo_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE nearby_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE playlist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;


-- CLEANUP OLD POLICIES (To ensure idempotency)
DO $$ 
DECLARE 
    r RECORD;
BEGIN 
    FOR r IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP 
        EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON ' || r.tablename; 
    END LOOP; 
END $$;

-- PUBLIC READ ACCESS (The Website)
CREATE POLICY "Public read destinations" ON destinations FOR SELECT USING (status = 'published' OR true); -- 'OR true' temporarily for dev visibility if status null, ideally status='published'
CREATE POLICY "Public read spots" ON photo_spots FOR SELECT USING (true);
CREATE POLICY "Public read nearby" ON nearby_places FOR SELECT USING (true);
CREATE POLICY "Public read page_sections" ON page_sections FOR SELECT USING (true);
CREATE POLICY "Public read articles" ON articles FOR SELECT USING (status = 'published');
CREATE POLICY "Public read checklists" ON checklists FOR SELECT USING (true);
CREATE POLICY "Public read playlists" ON playlists FOR SELECT USING (true);
CREATE POLICY "Public read playlist_items" ON playlist_items FOR SELECT USING (true);

-- PUBLIC WRITE ACCESS (Forms)
CREATE POLICY "Public insert contact" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert newsletter" ON newsletter_subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read user_roles" ON user_roles FOR SELECT USING (true); -- Needed for auth check on client


-- AUTHENTICATED USER ACCESS (Favorites)
CREATE POLICY "Users manage own favorites" ON favorites FOR ALL USING (auth.uid() = user_id);

-- ADMIN FULL ACCESS
-- Assuming admin has 'authenticated' role for MVP. 
-- Ideally check for specific claim or user_roles table, but simplifying to 'authenticated' as per existing login flow 
-- which effectively gates 'admin' pages nicely.
CREATE POLICY "Admin full destinations" ON destinations USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full spots" ON photo_spots USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full nearby" ON nearby_places USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full page_sections" ON page_sections USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full articles" ON articles USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full checklists" ON checklists USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full playlists" ON playlists USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full playlist_items" ON playlist_items USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full newsletter" ON newsletter_subscribers USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full contact" ON contact_messages USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full user_roles" ON user_roles USING (auth.role() = 'authenticated');


-- ==============================================================================
-- DONE
-- ==============================================================================
NOTIFY pgrst, 'reload schema';
