-- ==========================================
-- 7. TIPS & ARTICLES MANAGER
-- ==========================================

-- A. ARTICLES TABLE
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    category TEXT DEFAULT 'Tips',
    cover_image TEXT,
    content TEXT, -- Rich Text or HTML
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- B. CHECKLIST TEMPLATES (The "Planner")
CREATE TABLE IF NOT EXISTS checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT REFERENCES articles(id) ON DELETE CASCADE,
    title TEXT NOT NULL, -- e.g "Perlengkapan Wajib"
    items JSONB DEFAULT '[]'::jsonb, -- Array of strings or objects {text: "Tent", needed: true}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- RLS
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklists ENABLE ROW LEVEL SECURITY;

-- Public Read
CREATE POLICY "Public read articles" ON articles FOR SELECT USING (status = 'published');
CREATE POLICY "Public read checklists" ON checklists FOR SELECT USING (true);

-- Admin Write
CREATE POLICY "Admin all articles" ON articles USING (auth.role() = 'authenticated');
CREATE POLICY "Admin all checklists" ON checklists USING (auth.role() = 'authenticated');

NOTIFY pgrst, 'reload schema';
