-- ==========================================
-- 8. NEWSLETTER MANAGER PERMISSIONS
-- ==========================================

-- Admin Select Access
DROP POLICY IF EXISTS "Admin read subscribers" ON newsletter_subscribers;
CREATE POLICY "Admin read subscribers" 
ON newsletter_subscribers FOR SELECT 
USING (auth.role() = 'authenticated');

-- Ensure table exists (Refresher)
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    interests TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

NOTIFY pgrst, 'reload schema';
